version: '3.8'

services:
  wallet-service:
    build: .
    container_name: wallet-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
